### PR TITLE
fast-forward to version v0.5.3b-mavica

### PR DESCRIPTION
**Pull request by Lana-chan**
PR as requested by NightScript, feel free to amend the readme after merge

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
this is ultimately at your discretion, but imo version should not exceed 0.5.2 considering upstream has no version higher than this
i.e. v0.5.2-mavica1 or something like that would make more sense, at least until it is clear drenn has abandoned work on it (they still seem to be around)

**Comment by Lana-chan** [comment]
that's a very fair point, though i don't know if i want to backtrack that change in my own repo. i don't plan on making many more features for this (the main thing i wanted to do myself was the pocket camera mapper with DSi cameras), so i think this should be a change made by DS-Homebrew maintainers (which i'm ok being done downstream here, i have no qualms about any of my code being used as long as i'm credited somewhere)

**Comment by Lana-chan** [comment]
also just as a note the only places where the version is written down are in the readme and changelog files, while the makefile makes it so the version that actually gets written into the binary comes from `git describe`, so what actually names the version in the emulator itself is the latest git tag

**Comment by lifehackerhansol** [comment]
Doesn't matter to me either way, just an afterthought lol.

**Pull request merged**
